### ISSUE TITLE
GooglePlayServices_Leaderboard_LoadTopScores() will make the game crash

### ISSUE THREAD

**Issue by Applimazing** [YoYoGames/GMEXT-GooglePlayServices#11]
GooglePlayServices_Leaderboard_LoadTopScores() will make the game crash, but GooglePlayServices_Leaderboard_LoadPlayerCenteredScores() works.

Reproduce:
replace GooglePlayServices_Leaderboard_LoadPlayerCenteredScores() with GooglePlayServices_Leaderboard_LoadTopScores() in the GooglePlay Services demo from the marketplace and check that it crashes the game.

**Comment by jzavala-YYG** [comment]
Hi @Applimazing, thanks for reporting this ticket, It's already fixed, the issues was missing arguments in the extension function declaration.
