### ISSUE TITLE
Upgrade to a newer com.google.android.play:core SDK version

### ISSUE THREAD

**Issue by Jerome-Labbe-RedArtGames** [YoYoGames/GMEXT-GooglePlayServices#14]
Hello,

I have received the following message from Google regarding a published application built with SDK 34 that already uses the latest GMEXT-GooglePlayServices release available:

>There are new SDK issues for your game.
>
>com.google.android.play:core has added this note for core:1.8.0:
>
>Update your Play Core Maven dependency to an Android 14 compatible version! Your current Play Core library is incompatible >with targetSdkVersion 34 (Android 14), which introduces a backwards-incompatible change to broadcast receivers to improve >user security. As a reminder, from August 31, Google Play requires all new app releases to target Android 14. Update to the >latest Play Core library version dependency to avoid app crashes: https://developer.android.com/guide/playcore#playcore->migration
>
>You may not be able to release future versions of your app with this SDK version to production or open testing.

Best regards,

**Comment by jzavala-YYG** [comment]
Hi @Jerome-Labbe-RedArtGames 

I guess in the same project you are using the extension **_Mobile Review_**.

If yes, we already updated the project but at the moment of write this reply it's not on the marketplace you can download if directly from the repository.

I will close this ticket, if problem persists please re-open it.

Regards
