### ISSUE TITLE
[Request] Please add fire-and-forget (non-Immediate) versions to Achievement/Leaderboard calls

### ISSUE THREAD

**Issue by caroparo** [YoYoGames/GMEXT-GooglePlayServices#15]
For some reason, having many ds map related calls (async callbacks) seems to lead to higher ANR rate due to mutex lock issues.
As reducing callbacks seems to help relieve this issue, and not all games need to handle the callback values, I'd like to request for exposing callback-free versions of the following methods to GM:

> PlayGames.getAchievementsClient(activity).incrementImmediate(arch_id, (int)steps)
> PlayGames.getAchievementsClient(activity).revealImmediate(arch_id)
> PlayGames.getAchievementsClient(activity).setStepsImmediate(arch_id, (int)steps)
> PlayGames.getAchievementsClient(activity).unlockImmediate(arch_id)
> PlayGames.getLeaderboardsClient(activity).submitScoreImmediate(leader_id,(long) score, scoreTag)

References:
[AchievementsClient](https://developers.google.com/android/reference/com/google/android/gms/games/AchievementsClient#public-methods)
[LeaderboardsClient](https://developers.google.com/android/reference/com/google/android/gms/games/LeaderboardsClient#public-methods)

As the non-immediate versions don't fire callbacks, they can be new methods.

**Comment by jackerley** [comment]
Hi @caroparo I'm interested in the ANRs that you think are related to mutex lock issues. Can you provide any details as to what circumstances lead to problems here and any ANR callstacks that you may have? I would much rather fix those issues than provide workarounds that are particular to one specific case?

**Comment by caroparo** [comment]
@jackerley It makes sense to look into root causes instead of working around. However, this suggestion is from past experience and not current ANR issues.

Here's a newer ANR I'm currently facing with runtime v2024.4.1.202, where I redacted my package name to be "com.company.game".
[ANR log](https://github.com/YoYoGames/GMEXT-Firebase/issues/31#issuecomment-2306009002)

**Comment by jackerley** [comment]
I'm going to close this bug as I've put a fix in for the ANR, please feel free to open another ticker if you are having any more problems.
