### ISSUE TITLE
Async functions return Async IDs

### ISSUE THREAD

**Issue by dsk80004** [YoYoGames/GMEXT-GooglePlayServices#2]
The documentation in the wiki for all of the asynchronous calls says they return N/A which isn't true. They actually return a async id. This can be confusing for new comers to the async code. related, the documentation covering how the async events can be used should generally cover the use of async ids as its standard practice.

**Comment by DiasFranciscoA** [comment]
This should now by solved in the github wiki documentation, the included HTML documentation will update soon.
