### ISSUE TITLE
Crash when selecting the + icon in cloud save ui

### ISSUE THREAD

**Issue by efeberku** [YoYoGames/GMEXT-GooglePlayServices#4]
When we open cloud save ui and select the + icon the game crashes.

That's because the proguard deleting some of the required classes and we need to add default proguard rules for Google Play Services to solve this.

Proguard rules: https://developer.android.com/topic/google-play-instant/getting-started/support-play-games-services

**Comment by DiasFranciscoA** [comment]
The last commit to the main branch of the extension should have fixed the issue. Please let us know if that is the case, we were unable to reproduce it, but wanted to make sure that's the case before pushing a new update to the marketplace asset

**Comment by efeberku** [comment]
I already solved this by adding proguard rules weeks ago. If you added it then it will work. Also never forget to add proguard rules to extensions.
