### ISSUE TITLE
Extension's new proguard code injection values break LTS building process

### ISSUE THREAD

**Issue by caroparo** [YoYoGames/GMEXT-GooglePlayServices#5]
&lt;methods&gt; was treated like a xml tag, and caused &lt;/methods&gt; to be added and breaks.
It's supposedly fixed in monthly, but not in LTS.
A workaround is to add a proguard comment. #&lt;/methods&gt;

Also, it seems to be redundant as the native &lt;methods&gt; settings can be found in resulting configuration.txt that it is already included in proguard-android-optimize.txt-7.4.0.

Proguard output files can be found in:
C:\Users\{USERNAME}\AppData\Roaming\GameMakerStudio2-LTS\Cache\GMS2CACHE\{APP_CACHE}\android\Default\{APP_BUNDLE_ID}\build\outputs\mapping\release

```
Other tags like <init> also suffers from this issue.
For example:
<YYAndroidProguard>
-keepclassmembers public class * extends androidx.lifecycle.ViewModel { public <init>(...); }
#</init>
-keepclassmembers public class * extends androidx.lifecycle.AndroidViewModel { public <init>(...); }
#</init>
</YYAndroidProguard>
```

**Comment by DiasFranciscoA** [comment]
An update for the GooglePlayServices extension, which resolves the issue you've been experiencing, has just been launched. The version you should seek out is 2.1.3.
