### ISSUE TITLE
Incorrect callback is triggered

### ISSUE THREAD

**Issue by 5krad** [YoYoGames/GMEXT-GooglePlayServices#8]
![1](https://github.com/YoYoGames/GMEXT-GooglePlayServices/assets/86314276/b28eb5fa-f7ca-4fb0-8d38-3044962f6e54)

1. When the "Cancel" button is pressed at the GPGS login pop-up, "success" is triggered in the "GooglePlayServices_SignIn" case in the Async Social event even though the login actually failed.

2. In the Async Social event, "GooglePlayServices_SavedGames_Delete" case is triggered when GooglePlayServices_SavedGames_CommitAndClose() is called and failed.

Could you please check this issues?

**Comment by jzavala-YYG** [comment]
1. Success will be **_true_** most of cases, only if the request operation for any reason failed will be false, you should check **_isAuthenticated_** key to confirm if you user authentication succeed

2. Thanks for let us know. the wrong async event **_type_** was presented when the operation failed.
