### ISSUE TITLE
Add functionality to Google Play Services extension to show a user's Play Games Account level

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GMEXT-GooglePlayServices#9]

**Comment by jzavala-YYG** [comment]
This functionality it's already implemented

In this image you can see in the popup that the player has a level 7, and in the list we can see the key **_currentLevelNumber_** equal to 7
![image](https://github.com/YoYoGames/GMEXT-GooglePlayServices/assets/114691457/b17d8dac-caf1-4a89-974c-e0e6fb62989e)
